language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script: ./gradlew build test jacocoTestReport javadocs

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .travis-scripts/push-javadocs-to-gh-pages.sh

env:
  global:
    - REPO_NAME: Cheddarpuffs/Aeneas-KabaSuji
    - secure: YsrutuAQaQFOLTPhpyfsyn01F8ApBHDkTwwzh/OjLFYxPbI5JhGNWCUJMTZWt0v9zZDIgj07MIIwzJomfvtAMgghCkDXi9Aox6ltDjnzl5L6yAGKAiZovbDJVXazUUdhf/vSUPzSAO1jalRwO0W+AtLDgYCQcfSuAxgPB9fvNITFyl7tyt/Q+WsO81cqJnemM4RoikezHiSbcOmgfJ0or8pUHHIu+bf+HVQ5iaTfvoMprMWBY3XNPkPjkDpcYEOXjwVcISKhotkefBdALjFd+M1Q/WlDnbVB2lXQYzG73ZtP3KYAdikFu04w1cG9T+M+RSUHYSP/UP5zgrftuGcf63knjfctx6V6Sno1TSPi+azoVfi2Y88IxamaXGfiA7kD8hIUNld3BDyYj96SK/wWYVa8BcXzSCE0/3DeioEQ+qPBAmHAG9QTTdw97x/sg9NOKkJbAXngc044vZ2UHBxnPcPkwdRPDCJISqiRS/x/p8eu90VcB9QtZjZBXQilxJNR1O+PuutTzsjsYX4BfM2qpVvZxD2xAEZy0QFzV5SJjXfCzI/fdkP7v6HvsNHtMijzJ3H1KTZJUcVIHHaT/AEPaU99o2HPbxINVUZgxCmBJCGGLHetlp/skU2kHLSf6uiVeBWruRkAtUexFWsQ4w6R0bpIoWvk5W4B/hbEELa30AY=
